--- #YAML:1.0
name: Catalyst-Plugin-Authentication-Store-DBIC
version: 0.06
author:

abstract: Authentication and
authorization against a DBIx::Class or Class::DBI model.
license: perl
generated_by: Module::Build version 0.2702, without YAML.pm
