--- 
abstract: Authentication and authorization against a DBIx::Class or Class::DBI model.
author: David Kamholz, <dkamholz@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Plugin-Authentication-Store-DBIC
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst::Model::DBIC::Schema: 0
  Catalyst::Plugin::Authentication: 0.06
  Catalyst::Runtime: 0
  Class::Accessor::Fast: 0
  DBIx::Class: 0
  Set::Object: 1.14
version: 0.09
